version: "3.7"
services:
  
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: authority_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./authority
    container_name: authority
    working_dir: /root/
    env_file:
      - .env.local
    ports:
      - "4000:4000"
    depends_on:
      - postgres
