version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: authority_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - 5432:5432

  # spec:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.spec
  #   container_name: authority-spec
  #   working_dir: /opt/app
  #   environment:
  #     - DATABASE_URL=postgres://auth_user:auth_pass@db:5432/authority_db
  #   depends_on:
  #     - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./server
    container_name: authority-server
    working_dir: /root/
    env_file:
      - local.env
    ports:
      - "4000:4000"
    depends_on:
      - db
