version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: authority_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - 5432:5432

  migrator:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    container_name: migrator
    working_dir: /root/
    env_file:
      - local.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./server
    container_name: authority
    working_dir: /root/
    env_file:
      - local.env
    ports:
      - "4000:4000"
    depends_on:
      - db
      - migrator
